In [2]:
import pickle
import numpy as np
from scipy.io import loadmat

In [4]:
map_path = '/home/diego/Downloads/aggregated_floormaps.mat'
M = loadmat(map_path)
hfield = M['meanfloormap_appendages']

In [5]:
with open('test_floormap.p', 'wb') as f:
    pickle.dump({'hfield': hfield}, f)

In [8]:
with open('test_floormap.p', 'rb') as f:
    in_dict = pickle.load(f)
    im = in_dict['hfield']
    print(im)
    print(np.max(im))
    print(np.min(im))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
60.75142277857445
-60.792391445220574
